### ISSUE TITLE
The commit 1548dec destroys the compatibility symfony 3.4

### ISSUE THREAD

**Issue by ProhaRob** [jennevdmeer/intervention-image-bundle#1]
Hi,
i have updated the to your last commit and it destroys the compatibility to symfony 3.4:

```
!!  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "getRootNode" of class "Symfony\Component\Config\Definition\Builder\TreeBuilder". in [..]/vendor/impulze/intervention-image-bundle/src/DependencyInjection/Configuration.php:17
!!  Stack trace:
!!  #0 [..]/vendor/symfony/config/Definition/Processor.php(50): Impulze\Bundle\InterventionImageBundle\DependencyInjection\Configuration->getConfigTreeBuilder()
!!  #1 [..]/vendor/symfony/dependency-injection/Extension/Extension.php(96): Symfony\Component\Config\Definition\Processor->processConfiguration(Object(Impulze\Bundle\InterventionImageBundle\DependencyInjection\Configuration), Array)
!!  #2 [..]/vendor/impulze/intervention-image-bundle/src/DependencyInjection/ImpulzeInterventionImageExtension.php(15): Symfony\Component\DependencyInjection\Extension\Extension->processConfiguration(Object(Impulze\Bundle\InterventionImageBundle\Dependenc in [..]/vendor/impulze/intervention-image-bundle/src/DependencyInjection/Configuration.php on line 17
```

Symfony 3.4 has no getRootNode methode in TreeBuilder. How should i handle this issues without upgrading to Symfony 4.0

Best regards Robert

**Comment by jennevdmeer** [comment]
Hmm I should try and figure out the versioning things for real so this wouldn't happen.

What you can do for now is set composer's require to a specific commit like;
`composer require impulze/intervention-image-bundle:dev-master#341e62830d783c84410a0cf874b91c369184fa1`

I will take a look at sorting this for both versions.

**Comment by jennevdmeer** [comment]
Ok did some experimenting and this seems to be fixed now. Also created a version from now instead of `dev-master` it is recommended to switch over to avoid using the dev branch which could result into more issues in the future.
```
composer require impulze/intervention-image-bundle "^1.0"
```
This should change `composer.json` to said version and re download it.
