### ISSUE TITLE
Configuration key should be impulze_intervention_image not intervention_image

### ISSUE THREAD

**Issue by Lustmored** [jennevdmeer/intervention-image-bundle#3]
According to my project readme tells wrong configuration key - it should be 'impulze_intervention_image', not 'intervention_image'

**Comment by jennevdmeer** [comment]
What do you mean? Are you talking about semantics/best practices? Or doesn't it work? I've defined it as `intervention_image` in the config file:
https://github.com/jennevdmeer/intervention-image-bundle/blob/895fc77611d04dd0ec7888313713f0d1bc78240e/src/DependencyInjection/Configuration.php#L15

So I'm not sure where the expected `impulze` prefix would come from.

**Comment by Lustmored** [comment]
It didn't work for me and Symfony error message suggested change to `impulze_intervention_image`. After this change everything works as expected.

My resulting file (stored under config/packages/impulze_intervention_image.yaml):
```
impulze_intervention_image:
    driver: imagick # imagick or gd
```
just works.

I am using Symfony 5.0 if that's important. Full error message when using just intervention_image:
![image](https://user-images.githubusercontent.com/2358046/83143687-9e80ea80-a0f2-11ea-9f7b-108d279b0b28.png)

**Comment by jennevdmeer** [comment]
Welp. TIL. Symfony uses a snake cased bundle classname for creating the configuration index completely ignoring the value I highlighted.

Should be updated in a bit, thanks!
